spring:
  application:
    name: ReadFlow

  datasource:
    url: jdbc:mysql://localhost:3306/read_flow_library
    username: root
    password: padma@8503
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: mrpadma33@gmail.com
    password: wthx cymc mzro yugs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 500

